"""Add HR modules

Revision ID: 70daf467b3dd
Revises: 
Create Date: 2026-03-18 23:30:46.029528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70daf467b3dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('designation', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('department_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_foreign_key(None, 'departments', ['department_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_department_id'))
        batch_op.drop_column('department_id')
        batch_op.drop_column('address')
        batch_op.drop_column('designation')
        batch_op.drop_column('phone')
        batch_op.drop_column('profile_image')

    # ### end Alembic commands ###
